language: node_js
sudo: false
node_js:
  - 6.9.4
script:
  - npm test
  - cat ./coverage/lcov.info | coveralls
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install --depth=0
  - npm install coveralls
